# Generated by Django 3.0.8 on 2020-08-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200813_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='currentBid',
        ),
        migrations.AddField(
            model_name='bids',
            name='currentBid',
            field=models.IntegerField(blank=True, default=11),
            preserve_default=False,
        ),
    ]
