# Generated by Django 3.0.8 on 2020-08-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200816_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
